Remove dead code
Error: DEADCODE (CWE-561):
rsyslog-7.4.10/plugins/ommail/ommail.c:143: cond_null: Condition "(pNew = calloc(1UL, 16UL)) == NULL", taking true branch. Now the value of "pNew" is NULL.
rsyslog-7.4.10/plugins/ommail/ommail.c:153: null: At condition "pNew != NULL", the value of "pNew" must be NULL.
rsyslog-7.4.10/plugins/ommail/ommail.c:153: dead_error_condition: The condition "pNew != NULL" cannot be true.
rsyslog-7.4.10/plugins/ommail/ommail.c:154: dead_error_line: Execution cannot reach this statement "free(pNew);".