Remove unused variable
Error: COMPILER_WARNING:
rsyslog-7.4.10/plugins/pmaixforwardedfrom/pmaixforwardedfrom.c: scope_hint: In function 'parse'
rsyslog-7.4.10/plugins/pmaixforwardedfrom/pmaixforwardedfrom.c:72: warning: unused variable 'opening'